print("Complete Name:" + "Aldrick James A. Gicole")
print("Course:  " + "Computer Science")
print("Section: " + "CS1D")
print("Age: " + "16")
print("Birthday: " + "January 16, 2004")
print("Complete Home Address: " + "Purok 2-A Gusa Sampaguita St. Cagayan De Oro City")
print()
print("Complete Name:" + "Brandon Ian A. Gimolatan")
print("Course:  " + "Computer Science")
print("Section: " + "CS1D")
print("Age: " + "19")
print("Birthday: " + "August 21, 2004")
print("Complete Home Address: " + "Purok 4-B Grand Meadows Batangan Valencia City")
